config/routes.rb
# frozen_string_literal: true

# Rails routes
Rails.application.routes.draw do
  devise_for :users
  root to: 'conversations#index'

  resources :dashboards
  resources :conversations do
    resources :messages
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/conversation.rb
class Conversation < ApplicationRecord
  has_many :messages, dependent: :destroy

  scope :between, -> (sender_id, recipient_id) do
    where("(conversations.sender_id = ? AND   conversations.recipient_id =?) OR (conversations.sender_id = ? AND conversations.recipient_id =?)", sender_id, recipient_id, recipient_id, sender_id)
  end
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :conversation
  validates_presence_of :body, :conversation_id

  after_create_commit { broadcast_prepend_to "messages" }
  after_update_commit { broadcast_replace_to "messages" }
  after_destroy_commit { broadcast_remove_to "messages" }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
          :rememberable, :validatable
end

app/controllers/application_controller.rb
# frozen_string_literal: true

# Application Controller class
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_up_path_for(resource)
    root_path
  end

  def after_sign_in_path_for(resource)
    root_path
  end

  def after_sign_out_path_for(resource_or_scope)
    user_session_path
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/conversations_controller.rb
# frozen_string_literal: true

# Conversations Controller Class
class ConversationsController < ApplicationController
  before_action :authenticate_user!
  before_action :find_params, only: [:show]

  def index
    @other_users = User.where.not(id: current_user.id)
  end

  def create
    @conversation = Conversation.between(params[:sender_id], params[:recipient_id])&.first
    @conversation = Conversation.create!(conversation_params) if @conversation.nil?
    redirect_to conversation_path(@conversation.id)
  end

  def show
    @messages = @conversation.messages.order(created_at: :desc)
    @message = @conversation.messages.new
  end

  private

  def find_params
    @conversation = Conversation.find(params[:id])
  end

  def conversation_params
    params.permit(:sender_id, :recipient_id)
  end
end

app/controllers/dashboards_controller.rb
# frozen_string_literal: true

# Dashboards Controller
class DashboardsController < ApplicationController
  before_action :authenticate_user!

  def index; end
end

app/controllers/messages_controller.rb
# frozen_string_literal: true

# Messages Controller class
class MessagesController < ApplicationController
  before_action :find_params, only: %i[new create]

  def new
    @message = @conversation.messages.new
  end

  def create
    @message = @conversation.messages.new(message_params)
    @message.user_id = current_user.id
    @message.save
  end

  private

  def find_params
    @conversation = Conversation.find(params[:conversation_id])
  end

  def message_params
    params.require(:message).permit(:body)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/conversations_helper.rb
module ConversationsHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/homepage_helper.rb
module HomepageHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/conversations/_show.html.erb
<% if @messages.nil? %>
  <p>Start Conversation</p>
<% end %>

<div id="conversation-messages">
  <%= turbo_stream_from "messages" %>

  <%= turbo_frame_tag "messages" do %>
    <%= render @messages %>
  <% end %>
</div>

<div class="chat-form">
  <%= turbo_frame_tag "message_form" do %>
    <%= form_with(model: [@conversation, @conversation.messages.build], data: { controller: "reset-form", action: "turbo:submit-end->reset-form#reset" }, id: dom_id(@message)) do |form| %>
      <div class="d-flex align-items-center">
        <%= form.text_area :body, placeholder: 'Type your message content here', class: "form-control flex-grow mr-5" %>
        <%= form.submit class: "btn btn-success", data: { disable_with: false } %>
      </div>
    <% end %>
  <% end %>
</div>

app/views/conversations/index.slim
main#main
  .sidenav
    .d-flex.flex-column
      ul.chat-list
        - @other_users.each do |user|
          li.chat-list-item
            .mr-10.pl-15
              a.img-link.img-status href="#"
                = image_tag("default.png", width: '40px', height: '40px')
            div
              = link_to user.name, conversations_path(sender_id: current_user.id, recipient_id: user.id), method: :post, remote: true, class: 'font-w600'              

  .main
    .d-flex.flex-column
      #content_area

app/views/conversations/show.js.erb
document.getElementById("content_area").innerHTML = '<%=j render "show" %>';

app/views/dashboards/index.html.erb
<main id="main-container">
  <div class="row">
    <div class="col-md-3 border-right border-bottom">
      <div class="row d-flex flex-column">
        <div class="p-15 d-flex align-items-center justify-content-between">
          <div class="d-flex align-items-center">
            <i class="fa fa-share pl-4"></i>
            <a class="ml-2" href="#">New Chat</a>
          </div>
          <div class="ml-20">
            <button type="button" class="btn">
              <i class="fa fa-search"></i>
              <a class="ml-2" href="#">Search</a>
            </button>
          </div>
        </div>
      </div>
    </div>

    <div class="col-md-9 border-bottom">
      <div class="row d-flex flex-column">
        <div class="p-15 d-flex align-items-center justify-content-between">
          <div class="d-flex align-items-center">
            <a class="ml-20" href="#">Inbox</a>
            <a class="ml-20" href="#">Texts</a>
            <a class="ml-20" href="#">Flagged</a>
          </div>
          <div class="ml-20">
            <button type="button" class="btn">
              <i class="fa fa-phone"></i>
            </button>
            <button type="button" class="btn">
              <i class="fa fa-comment"></i>
            </button>
            <button type="button" class="btn">
              <i class="fa fa-envelope"></i>
            </button>
            <button type="button" class="btn">
              <i class="fa fa-share"></i>
            </button>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div id="chat-section" class="row border-bottom">
    <div class="col-md-3 border-right chat-contacts">
      <div class="row d-flex flex-column">
        <ul class="chat-list">
          <% @other_users.each do |user| %>
            <li class="chat-list-item">
              <div class="mr-10 pl-15">
                <a class="img-link img-status" href="#">
                  <%= image_tag("default.png", class: "img-avatar", width: '40px', height: '40px') %>
                </a>
              </div>
              <div>
                <%= link_to user.name, conversations_path(sender_id: current_user.id, recipient_id: user.id), method: :post, remote: true, class: "font-w600" %>
                <div class="font-size-xs text-muted">
                  <!-- Hello there! -->
                </div>
              </div>
            </li>
          <% end %>
        </ul>
      </div>
    </div>

    <div class="col-md-9 d-flex flex-column">
      <!-- <div class="row d-flex flex-column"> -->
        <div id="content_area" class="p-15 flex-grow-1 text-wrap-break-word overflow-y-auto"></div>
      <!-- </div> -->
    </div>
  </div>
</main>

app/views/layouts/application.html.slim
doctype html
html
  head
    meta content=("text/html; charset=UTF-8") http-equiv="Content-Type"
    title Covaxsys
    meta content="width=device-width,initial-scale=1" name="viewport"
    = csrf_meta_tags
    = csp_meta_tag

    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = stylesheet_pack_tag 'application', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'

  body
    = render 'shared/header'
    = yield

app/views/messages/_message.html.erb
<%= turbo_frame_tag dom_id(message) do %>
  <div class="row mx-10">
    <div>
      <span class="text-primary mr-4"><%= User.find(message.user_id).name %></span>
      <span class="ml-10"><%= message.body %></span>
    </div>
  </div>
<% end %>

app/views/shared/_header.slim
header#header.fixed-top
  .container-fluid.d-flex
    .logo.mr-auto
      h1.text-light
        = link_to 'MESSAGE PLATFORM', root_path
    nav.nav-menu.d-none.d-lg-block
      ul
        li
          - if user_signed_in?
            a.font-italic
              span Logged in by
              span.pl-1.font-weight-bold= current_user.name
        li.get-started
          - if user_signed_in?
            = link_to 'Logout', destroy_user_session_path, method: :delete
          - else
            = link_to 'Login', new_user_session_path

app/views/shared/_sidebar.slim
.sidenav
  = link_to 'Dashboard', dashboards_path